/*
 * Arduino Uno R3/R4 - Serial Communication Base Template (v5)
 * Supports both v5 delimited text format and v4 JSON format
 * Generated by Hydroponics v5 Firmware Generator
 */

#include <ArduinoJson.h>

// === CONFIGURATION ===
#define SERIAL_BAUD 9600
#define JSON_BUFFER_SIZE 512
#define FIRMWARE_VERSION "1.0-v5"

// GENERATOR_INCLUDES_PLACEHOLDER

// === CAPABILITIES ===
// GENERATOR_CAPABILITIES_ARRAY_PLACEHOLDER

// === RESET FUNCTION ===
void(* resetFunc) (void) = 0;

// === UTILITY FUNCTIONS ===
int freeMemory() {
  extern int __heap_start, *__brkval;
  int v;
  return (int) &v - (__brkval == 0 ? (int) &__heap_start : (int) __brkval);
}

// GENERATOR_FUNCTIONS_PLACEHOLDER

// === SETUP ===
void setup() {
  Serial.begin(SERIAL_BAUD);
  while (!Serial) {
    ; // Wait for serial port to connect
  }
  Serial.println("{\"ok\":1,\"msg\":\"Arduino Uno Ready\"}");
}

// === MAIN LOOP ===
void loop() {
  if (Serial.available() > 0) {
    String input = Serial.readStringUntil('\n');
    input.trim();

    if (input.length() > 0) {
      processCommand(input);
    } else {
      while(Serial.available() > 0) {
        Serial.read();
      }
    }
  }
}

// === COMMAND PARSER ===
void processCommand(String input) {
  // v5: Try delimited text format first (e.g., "ANALOG|A0", "PING")
  // v4: Fall back to JSON format for backward compatibility
  
  char cmdBuffer[64];
  strncpy(cmdBuffer, input.c_str(), sizeof(cmdBuffer) - 1);
  cmdBuffer[sizeof(cmdBuffer) - 1] = '\0';
  
  // Find delimiter position
  char* delimiter = strchr(cmdBuffer, '|');
  const char* cmd = cmdBuffer;
  
  // Check if this is a delimited text command
  if (delimiter != NULL || input.indexOf('{') == -1) {
    // v5 Delimited Text Format
    
    // === SYSTEM COMMANDS ===
    
    if (strcmp(cmd, "PING") == 0) {
      Serial.println("{\"ok\":1,\"pong\":1}");
    }
    
    else if (strcmp(cmd, "INFO") == 0) {
      Serial.print("{\"ok\":1,\"up\":");
      Serial.print(millis());
      Serial.print(",\"mem\":");
      Serial.print(freeMemory());
      Serial.print(",\"ver\":\"");
      Serial.print(FIRMWARE_VERSION);
      Serial.print("\",\"capabilities\":[");
      for (int i = 0; i < CAPABILITIES_COUNT; i++) {
        Serial.print("\"");
        Serial.print(CAPABILITIES[i]);
        Serial.print("\"");
        if (i < CAPABILITIES_COUNT - 1) Serial.print(",");
      }
      Serial.println("]}");
    }
    
    else if (strcmp(cmd, "STATUS") == 0) {
      Serial.print("{\"ok\":1,\"status\":\"running\",\"up\":");
      Serial.print(millis());
      Serial.println("}");
    }
    
    else if (strcmp(cmd, "RESET") == 0) {
      Serial.println("{\"ok\":1,\"msg\":\"Resetting...\"}");
      delay(100);
      resetFunc();
    }
    
    // GENERATOR_DISPATCHER_PLACEHOLDER
    
    else {
      Serial.println("{\"ok\":0,\"error\":\"ERR_INVALID_COMMAND\"}");
    }
    
  } else {
    // v4 JSON Format (backward compatibility)
    StaticJsonDocument<JSON_BUFFER_SIZE> doc;
    DeserializationError error = deserializeJson(doc, input);
    
    if (error) {
      Serial.println("{\"ok\":0,\"error\":\"ERR_INVALID_FORMAT\"}");
      while(Serial.available() > 0) Serial.read();
      return;
    }
    
    const char* jsonCmd = doc["cmd"];
    
    if (!jsonCmd) {
      Serial.println("{\"ok\":0,\"error\":\"ERR_MISSING_PARAMETER\"}");
      while(Serial.available() > 0) Serial.read();
      return;
    }
    
    // === SYSTEM COMMANDS (v4 JSON compatibility) ===
    
    if (strcmp(jsonCmd, "PING") == 0) {
      doc.clear();
      doc["ok"] = 1;
      doc["pong"] = 1;
      serializeJson(doc, Serial);
      Serial.println();
    }
    
    else if (strcmp(jsonCmd, "INFO") == 0) {
      doc.clear();
      doc["ok"] = 1;
      doc["up"] = millis();
      doc["mem"] = freeMemory();
      doc["ver"] = FIRMWARE_VERSION;
      JsonArray caps = doc.createNestedArray("capabilities");
      for (int i = 0; i < CAPABILITIES_COUNT; i++) {
        caps.add(CAPABILITIES[i]);
      }
      serializeJson(doc, Serial);
      Serial.println();
    }
    
    else if (strcmp(jsonCmd, "STATUS") == 0) {
      doc.clear();
      doc["ok"] = 1;
      doc["status"] = "running";
      doc["up"] = millis();
      serializeJson(doc, Serial);
      Serial.println();
    }
    
    else if (strcmp(jsonCmd, "RESET") == 0) {
      doc.clear();
      doc["ok"] = 1;
      doc["msg"] = "Resetting...";
      serializeJson(doc, Serial);
      Serial.println();
      delay(100);
      resetFunc();
    }
    
    // GENERATOR_DISPATCHER_PLACEHOLDER (v4 JSON commands)
    
    else {
      doc.clear();
      doc["ok"] = 0;
      doc["error"] = "Unknown command";
      serializeJson(doc, Serial);
      Serial.println();
    }
  }
}
